-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: entra_sso_full_up.sql
-- Purpose:   Full schema for Microsoft Entra ID OIDC SSO.
--
-- Creates:
--   1. sso_state table — short-lived PKCE/CSRF state tokens
--   2. Inserts required app_settings keys (safe on existing deployments)
--   3. RLS policies for sso_state (service role only)
--   4. Auto-cleanup function + scheduled job for expired state rows
--
-- Run in Supabase SQL editor.
-- Safe to run multiple times (all DDL uses IF NOT EXISTS / ON CONFLICT DO NOTHING).
-- ─────────────────────────────────────────────────────────────────────────────

-- ── 1. sso_state — stores PKCE code_verifier keyed by state nonce ────────────
--
--  state         Random base64url string generated by /api/entra-login.
--                Acts as both the OAuth state parameter (CSRF) and the lookup key.
--  code_verifier The PKCE code_verifier generated alongside the state.
--                Retrieved by /api/entra-callback to complete the PKCE exchange.
--  expires_at    10 minutes from creation. Rows older than this are rejected + deleted.
--  created_at    Audit trail only.

CREATE TABLE IF NOT EXISTS sso_state (
  state          TEXT        PRIMARY KEY,
  code_verifier  TEXT        NOT NULL,
  expires_at     TIMESTAMPTZ NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index to make expiry cleanup efficient
CREATE INDEX IF NOT EXISTS sso_state_expires_at_idx ON sso_state (expires_at);

-- ── 2. Row-Level Security for sso_state ──────────────────────────────────────
--
-- This table is only accessed by the service role (serverless functions).
-- The anon key / authenticated users must never be able to read or write it.
-- Enabling RLS with NO user policies means all client requests are blocked;
-- only the service role (which bypasses RLS) can access the table.

ALTER TABLE sso_state ENABLE ROW LEVEL SECURITY;

-- Drop any stale policies before recreating (idempotent)
DROP POLICY IF EXISTS sso_state_deny_all ON sso_state;

-- Explicitly deny all authenticated and anonymous users
CREATE POLICY sso_state_deny_all ON sso_state
  FOR ALL
  TO public
  USING (false);

-- ── 3. app_settings rows ──────────────────────────────────────────────────────
--
-- All settings controlled from the Admin panel.
-- ON CONFLICT DO NOTHING = existing values are preserved on re-run.

-- Ensure app_settings has an updated_at column (safety — may already exist)
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

INSERT INTO app_settings (key, value, updated_at) VALUES
  ('sso_provider',            'none',  NOW()),
  ('entra_tenant_id',         '',      NOW()),
  ('entra_client_id',         '',      NOW()),
  ('entra_client_secret_enc', '',      NOW()),
  ('entra_redirect_uri',      '',      NOW()),
  ('entra_tenant_hint',       '',      NOW())
ON CONFLICT (key) DO NOTHING;

-- ── 4. Cleanup function — removes expired sso_state rows ─────────────────────
--
-- Called inline from /api/entra-callback.ts after validating each request.
-- Also scheduled below to run hourly so the table never bloats.

CREATE OR REPLACE FUNCTION cleanup_expired_sso_state()
RETURNS void
LANGUAGE sql
SECURITY DEFINER
AS $$
  DELETE FROM sso_state WHERE expires_at < NOW();
$$;

-- ── 5. Scheduled hourly cleanup (pg_cron — available on Supabase Pro) ─────────
--
-- Comment out if you are on the Supabase free tier (pg_cron not available).
-- The inline cleanup in /api/entra-callback still runs on every login.
--
-- SELECT cron.schedule(
--   'cleanup-sso-state-hourly',
--   '0 * * * *',
--   'SELECT cleanup_expired_sso_state()'
-- );

-- ─────────────────────────────────────────────────────────────────────────────
-- ROLLBACK: run entra_sso_full_down.sql
-- ─────────────────────────────────────────────────────────────────────────────
